export const KAFKA_SERVICE = 'KAFKA_SERVICE';
export const AUTH_SERVICE_CLIENT = 'AUTH_SERVICE_CLIENT';
export const USER_SERVICE_CLIENT = 'USER_SERVICE_CLIENT';
export const AUTH_CREDENTIAL_REPOSITORY = 'AUTH_CREDENTIAL_REPOSITORY';
export const USER_PROFILE_REPOSITORY = 'USER_PROFILE_REPOSITORY';
export const OUTBOX_REPOSITORY = 'OUTBOX_REPOSITORY';
